### ISSUE TITLE
ファイル名の文字化け

### ISSUE THREAD

**Issue by ore-public** [kazuhisa/zip4win#1]
「ドメイン外注仕入発注申請書.xlsx」　→　「ト■メイン外注仕入発注申請書.xlsx」
「動作レスポンス測定報告書_20151119.docx」　→　「動作レスホ■ンス測定報告書_20151119.docx」

**Comment by kazuhisa** [comment]
濁点がダメみたいですね。
よくある話だからどっかにノウハウが転がってないかなぁ。
